version: '3.0'
services:
  broker:
    image: rabbitmq
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=1234
  producer:
    build: amqp
    command: "python /app/producer.py --host=broker --user=user"
    environment:
      - AMQP_PWD=1234
      - PYTHONUNBUFFERED=1
    restart: on-failure
    depends_on:
      - broker
  consumer:
    build: amqp
    command: "python /app/consumer.py --host=broker --user=user"
    environment:
      - AMQP_PWD=1234
      - PYTHONUNBUFFERED=1
    restart: on-failure
    depends_on:
      - producer